name: Clang-tidy linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: clang-tidy check
        uses: muxee/clang-tidy-action@0.0.1-rc1

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: installs dep
      run: sudo apt update && sudo apt install -y clang-6.0 clang-tidy
    - name: make
      run: make -C Program-2/
