name: Clang-tidy linter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: make check-style
      run: make check-style -C Program-2/
    - name: make
      run: make -C Program-2/
